# Generated by Django 5.1.5 on 2025-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_revokedtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
