# Generated by Django 5.1.5 on 2025-01-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_userprofile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
