# Generated by Django 5.1.5 on 2025-01-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
